#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICONBLUE15                          2
#define IDI_ICONGRAY							5
#define IDD_OPTIONS                             103
#define IDD_MAIN                                105
#define IDM_RESTORE                             200
#define IDM_AUTOMATIC                           201
#define IDM_MANUAL                              202
#define IDM_QUIT                                203
#define IDM_SYNCNOW								204
#define IDM_TRAYMENU                            300
#define IDP_SYNCSTATUS                          1002
#define IDL_SYNCINT                             1004
#define IDH_OPERMODEHOTKEY                      1006
#define IDC_AUTOSYNCSTARTUP                     1007
#define IDC_STARTMINIMIZED                      1008
#define IDC_FUTUREOPT3	                        1009
#define IDC_UTCOFFSET                           1011
#define IDE_UTCOFFSET                           1012
#define IDH_MANSYNCHOTKEY                       1014
#define IDB_OK                                  1050
#define IDB_CANCEL                              1051
#define IDT_NEXTSYNC                            1053
#define IDP_NEXTSYNC                            1055
#define IDB_DEFAULTS                            1100
#define IDB_SYNCNOW                             1101
#define IDB_MODE                                1102
#define IDB_OPTIONS                             1103
#define IDT_NOMANUAL                            1104
#define IDT_OPERMODE                            1105
#define IDT_SYSUTC                              1130
#define IDT_SIMUTC                              1131
#define IDT_SIMSTATUS                           1132
#define IDT_LASTSYNC                            1133
#define IDT_TOSYNC								1134
#define IDT_SYNCSTATUS							1135
